-- Create a table to store the history of feedback/revision notes
CREATE TABLE IF NOT EXISTS video_feedback_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id BIGINT REFERENCES videos(id) ON DELETE CASCADE,
  feedback_text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  status_context TEXT -- e.g. 'Video Editing', 'Revision Requested'
);

-- Enable RLS (optional, but good practice if we expose this table to client)
ALTER TABLE video_feedback_log ENABLE ROW LEVEL SECURITY;

-- Policy: Allow read access to authenticated users (admin, etc.)
CREATE POLICY "Enable read access for authenticated users" ON video_feedback_log
  FOR SELECT TO authenticated USING (true);

-- Policy: Allow insert from server actions (service role ignores RLS, but for good measure)
CREATE POLICY "Enable insert for authenticated users" ON video_feedback_log
  FOR INSERT TO authenticated WITH CHECK (true);
