-- ============================================================================
-- On-Time Delivery tracking
-- Run this in the Supabase SQL Editor.
--
-- WHY THIS EXISTS
-- Before this migration the database recorded no delivery timestamp at all, so
-- "did we deliver on time" could only be approximated from the lecturer's
-- feedback-form submission date -- a date that lags real delivery by up to 204
-- days. See AI_README.md section 11.
--
-- WHAT IT ADDS
--   1. videos.due_date     -- per-video deadline (NULL = inherit project due date)
--   2. videos.delivered_at -- first hand-off to the lecturer, stamped automatically
--   3. due_date_changes    -- history of deadline renegotiations
--
-- This is forward-looking only. Every existing row gets NULL: delivery dates for
-- past work were never recorded and cannot be reconstructed.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Per-video deadline
-- ---------------------------------------------------------------------------
-- NULL means "inherit projects.due_date". Only classes with staggered or weekly
-- deliveries need to set this per video; ordinary projects leave it empty.
ALTER TABLE public.videos
  ADD COLUMN IF NOT EXISTS due_date DATE;

COMMENT ON COLUMN public.videos.due_date IS
  'Per-video deadline. NULL means inherit projects.due_date. Used for classes with weekly or staggered delivery.';

-- ---------------------------------------------------------------------------
-- 2. Delivery timestamp
-- ---------------------------------------------------------------------------
ALTER TABLE public.videos
  ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ;

COMMENT ON COLUMN public.videos.delivered_at IS
  'First time this video was handed to the lecturer (status entered Review). Set once by trigger, never overwritten. NULL for anything delivered before this column existed.';

-- A trigger, not application code, because there are multiple paths that move a
-- video into Review (the "mark ready for review" button, the video edit form's
-- status dropdown, and the lecturer-facing actions). Stamping it in one server
-- action is exactly how the previous logging ended up covering 1 video out of 393.
CREATE OR REPLACE FUNCTION public.stamp_video_delivered_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  -- Only the FIRST hand-off counts. Re-delivery after a revision must not
  -- overwrite it, otherwise a revision round would silently reset punctuality.
  IF NEW.delivered_at IS NOT NULL THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF NEW.status = 'Review' THEN
      NEW.delivered_at := NOW();
    END IF;
  ELSIF TG_OP = 'UPDATE' THEN
    -- Require a genuine TRANSITION into Review. Without the OLD/NEW comparison,
    -- any unrelated edit to a video already sitting in Review would stamp it with
    -- today's date -- inventing a delivery date for work handed over long ago.
    -- updateVideo() always includes `status` in its SET list, so this trigger
    -- fires on every video edit and the guard matters.
    IF NEW.status = 'Review' AND OLD.status IS DISTINCT FROM NEW.status THEN
      NEW.delivered_at := NOW();
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_stamp_video_delivered_at ON public.videos;
CREATE TRIGGER trg_stamp_video_delivered_at
  BEFORE INSERT OR UPDATE OF status ON public.videos
  FOR EACH ROW
  EXECUTE FUNCTION public.stamp_video_delivered_at();

-- Videos sitting in Review right now got there before this trigger existed. They
-- keep delivered_at = NULL and are reported as "Not Tracked" rather than being
-- given a fabricated date. They will never gain a delivery date, which is correct:
-- we know they were delivered, but not when.

-- ---------------------------------------------------------------------------
-- 3. Deadline renegotiation history
-- ---------------------------------------------------------------------------
-- The on-time metric judges against the LATEST agreed deadline, so the team is
-- not penalised for changes the lecturer asked for. This table keeps those
-- changes visible as a separate number instead of hiding them.
CREATE TABLE IF NOT EXISTS public.due_date_changes (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id    BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
  video_id      BIGINT REFERENCES public.videos(id) ON DELETE CASCADE,
  old_due_date  DATE,
  new_due_date  DATE,
  changed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  changed_by    UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_due_date_changes_project ON public.due_date_changes(project_id);
CREATE INDEX IF NOT EXISTS idx_due_date_changes_video   ON public.due_date_changes(video_id);

-- SECURITY DEFINER so the insert succeeds regardless of the caller's RLS grants
-- on this table -- the trigger is the only writer.
CREATE OR REPLACE FUNCTION public.log_project_due_date_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.due_date IS DISTINCT FROM OLD.due_date THEN
    INSERT INTO public.due_date_changes (project_id, old_due_date, new_due_date, changed_by)
    VALUES (NEW.id, OLD.due_date, NEW.due_date, auth.uid());
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_log_project_due_date_change ON public.projects;
CREATE TRIGGER trg_log_project_due_date_change
  AFTER UPDATE OF due_date ON public.projects
  FOR EACH ROW
  EXECUTE FUNCTION public.log_project_due_date_change();

CREATE OR REPLACE FUNCTION public.log_video_due_date_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.due_date IS DISTINCT FROM OLD.due_date THEN
    INSERT INTO public.due_date_changes (project_id, video_id, old_due_date, new_due_date, changed_by)
    VALUES (NEW.project_id, NEW.id, OLD.due_date, NEW.due_date, auth.uid());
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_log_video_due_date_change ON public.videos;
CREATE TRIGGER trg_log_video_due_date_change
  AFTER UPDATE OF due_date ON public.videos
  FOR EACH ROW
  EXECUTE FUNCTION public.log_video_due_date_change();

-- ---------------------------------------------------------------------------
-- 4. RLS -- matches the pattern used by video_feedback_log
-- ---------------------------------------------------------------------------
ALTER TABLE public.due_date_changes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.due_date_changes;
CREATE POLICY "Enable read access for authenticated users" ON public.due_date_changes
  FOR SELECT TO authenticated USING (true);

-- No INSERT policy on purpose: rows are written only by the SECURITY DEFINER
-- triggers above, never directly by the application.

-- ---------------------------------------------------------------------------
-- 5. Verification -- expect all-NULL delivery dates until the team starts
--    moving videos into Review after this migration.
-- ---------------------------------------------------------------------------
-- SELECT COUNT(*) AS videos_total,
--        COUNT(delivered_at) AS with_delivery_date,
--        COUNT(due_date) AS with_own_due_date
-- FROM public.videos;
