-- Run this in Supabase SQL Editor to support assigning lecturers to faculties

create table public.lecturer_faculty_join (
  id bigint generated by default as identity primary key,
  lecturer_id bigint references public.lecturers(id) on delete cascade not null,
  faculty_id bigint references public.faculties(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(lecturer_id, faculty_id)
);

-- Enable RLS (Optional, recommended)
alter table public.lecturer_faculty_join enable row level security;
create policy "Allow all access for authenticated users" on public.lecturer_faculty_join for all using (true);
