-- db_schema_academic_years.sql
--
-- Adds the academic-year layer above terms, and the notion of ONE active year that
-- scopes the dashboard, analytics and workload by default.
--
-- Run this once in the Supabase SQL Editor. It is idempotent — re-running it will not
-- duplicate years, re-link terms, or move the active flag.
--
-- Why a table rather than parsing the term name: the term codes happen to encode the
-- year today ('1251' -> '125'), but nothing enforces that, and a naming change would
-- silently regroup every historical figure. A real table also gives the active flag
-- somewhere to live and years a stable display name for reports.

-- ---------------------------------------------------------------------------
-- 1. The years themselves
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS academic_years (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,          -- '2025/2026' — what humans and reports see
  code        TEXT NOT NULL UNIQUE,          -- '125'       — the term-name prefix it owns
  is_active   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Exactly one year can be active, enforced by the database rather than trusted to
-- application code. A partial unique index permits any number of FALSE rows and at
-- most one TRUE, so a careless UPDATE cannot leave two years active at once.
CREATE UNIQUE INDEX IF NOT EXISTS academic_years_one_active
  ON academic_years (is_active) WHERE is_active;

-- ---------------------------------------------------------------------------
-- 2. Link terms to years
-- ---------------------------------------------------------------------------

ALTER TABLE terms
  ADD COLUMN IF NOT EXISTS academic_year_id BIGINT REFERENCES academic_years(id);

CREATE INDEX IF NOT EXISTS terms_academic_year_id_idx ON terms (academic_year_id);

-- ---------------------------------------------------------------------------
-- 3. Seed the two years that exist
-- ---------------------------------------------------------------------------

INSERT INTO academic_years (name, code) VALUES
  ('2025/2026', '125'),
  ('2026/2027', '126')
ON CONFLICT (name) DO NOTHING;

-- 1263 does not exist yet; the 2026/2027 year is only complete with it.
INSERT INTO terms (name)
SELECT '1263'
WHERE NOT EXISTS (SELECT 1 FROM terms WHERE name = '1263');

-- ---------------------------------------------------------------------------
-- 4. Backfill: attach every term to its year by name prefix
-- ---------------------------------------------------------------------------
--
-- Only fills terms that have no year yet, so a term someone has since reassigned by
-- hand is never dragged back to the prefix-derived answer.

UPDATE terms t
SET    academic_year_id = y.id
FROM   academic_years y
WHERE  t.academic_year_id IS NULL
  AND  LEFT(t.name, 3) = y.code;

-- ---------------------------------------------------------------------------
-- 5. Set the active year
-- ---------------------------------------------------------------------------
--
-- 2026/2027 is current: work on 1261 has already begun. Note this does NOT hide the
-- 2025/2026 projects that are still running — the app treats those as carry-over and
-- keeps them visible and labelled. See AI_README §13.

UPDATE academic_years SET is_active = FALSE WHERE is_active;
UPDATE academic_years SET is_active = TRUE  WHERE code = '126';

-- ---------------------------------------------------------------------------
-- 6. RLS — read for any signed-in user, writes via authenticated server actions
-- ---------------------------------------------------------------------------

ALTER TABLE academic_years ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for authenticated users" ON academic_years;
CREATE POLICY "Enable read access for authenticated users" ON academic_years
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Enable write access for authenticated users" ON academic_years;
CREATE POLICY "Enable write access for authenticated users" ON academic_years
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------------
-- Verify
-- ---------------------------------------------------------------------------
--
--   SELECT y.name, y.code, y.is_active, COUNT(t.id) AS terms
--   FROM   academic_years y LEFT JOIN terms t ON t.academic_year_id = y.id
--   GROUP  BY y.id, y.name, y.code, y.is_active
--   ORDER  BY y.code;
--
-- Expected: 2025/2026 -> 3 terms (1251, 1252, 1253), active = false
--           2026/2027 -> 3 terms (1261, 1262, 1263), active = true
